version: "2.4"

services:
  app:
    container_name: desserts-external
    entrypoint: ['java', '-jar', '-Dspring.profiles.active=beta', 'app.jar']
    build: .
    ports:
      - 8080:8080
    networks:
      - database
    depends_on:
      dev-db:
        condition: service_healthy
  dev-db:
    image: mysql:5.7.31
    volumes:
      - /var/lib/mysql
      - ./external-api/dev/:/docker-entrypoint-initdb.d
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: desserts
      MYSQL_USER: desserts_beta_svc
      MYSQL_PASSWORD: rP0h3C27C046wF5j6cOJ
    networks:
      - database
    ports:
      - 3306:3306
    healthcheck:
      test: ['CMD', '/usr/bin/mysql', '--host=dev-db', '--port=3306', '--user=root', '--password=1234', '-e', 'show databases;']
      interval: 30s
      timeout: 10s
      retries: 5

networks:
  database: