version: "2.4"

services:
  proxy:
    container_name: desserts-external-proxy
    image: nginx:latest
    ports:
      - 80:80
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
    networks:
      - external
    depends_on:
      app:
        condition: service_healthy
  app:
    container_name: desserts-external
    entrypoint: ['java', '-jar', '-Dspring.profiles.active=beta', 'app.jar']
    build:
      context: ..
      args:
        module: external-api
    image: desserts-external
    networks:
      - external
    depends_on:
      dev-db:
        condition: service_healthy
    healthcheck:
      test: ['CMD', 'curl', 'http://localhost:8080/healthcheck']
      interval: 30s
      timeout: 10s
      retries: 5
  dev-db:
    container_name: desserts-dev-db
    image: mysql:5.7.31
    volumes:
      - /var/lib/mysql
      - ./docker/database:/docker-entrypoint-initdb.d
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: desserts
      MYSQL_USER: desserts_beta_svc
      MYSQL_PASSWORD: rP0h3C27C046wF5j6cOJ
    networks:
      - external
    ports:
      - 3306:3306
    healthcheck:
      test: ['CMD', '/usr/bin/mysql', '--host=dev-db', '--port=3306', '--user=root', '--password=1234', '-e', 'show databases;']
      interval: 30s
      timeout: 10s
      retries: 5

networks:
  external: