version: "2.4"

services:
  proxy:
    container_name: desserts-external-proxy
    image: nginx:latest
    ports:
      - 80:80
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
    networks:
      - external
    depends_on:
      app:
        condition: service_healthy
  app:
    container_name: desserts-external
    build:
      context: ..
      args:
        module: external-api
    image: desserts-external
    networks:
      - external
    healthcheck:
      test: ['CMD', 'curl', 'http://localhost:8080/healthcheck']
      interval: 30s
      timeout: 10s
      retries: 5

networks:
  external: